### REGISTER
POST http://localhost:3000/doctor/auth/register
Content-Type: application/json

{
    "username":"doctor1",
    "password": "doctor1",
    "name": "dr.budi1",
    "specialization":"umum",
    "imageURL": "abc",
    "hospital": "abc"
}

### LOGIN
POST http://localhost:3000/doctor/auth/login
Content-Type: application/json

{
    "username":"doctor",
    "password": "doctor"
}

### GET DOCTOR DATA BY ID
GET http://localhost:3000/doctor/a9263cd4-7de4-4236-a35b-c4245018cbbb

### GET ALL DOCTOR BY HOSPITAL
GET http://localhost:3000/doctor?hospital=abc