### REGISTER
POST http://localhost:3000/patient/auth/register
Content-Type: application/json

{
    "username":"patient",
    "password": "patient",
    "name": "patient1",
    "imageURL": "abc"
}

### LOGIN
POST http://localhost:3000/patient/auth/login
Content-Type: application/json

{
    "username":"patient",
    "password": "patient"
}

### GET PATIENT DATA
GET http://localhost:3000/patient/84e09f67-560b-48f8-80c7-9da6349d6eda