version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=healthcare
  app:
    image: healthcare   # Use the image you built earlier
    command: sh -c "npm run start"
    ports:
      - "3000:3000"            # Map the port used by your application to the host machine
    volumes:
      - ./dist:/app/dist       # Mount the 'dist' directory as a volume inside the container
    environment:
      - DATABASE_URL=postgres://postgres:admin@postgres:5432/healthcare
      - JWT_KEY=ada2a4c6349d5a9f742ef16036ff18a1a37165ddbd4f45fe4f34c9caf80d33f3
      - SALT=10
    depends_on:
      - postgres
volumes:
  postgres:
    driver: local
